In [17]:
import torch
import torch.nn as nn

In [2]:
x = torch.rand(2,4,5)

In [3]:
x

tensor([[[0.9361, 0.2419, 0.8914, 0.6563, 0.8088],
         [0.8205, 0.0816, 0.7850, 0.3263, 0.6876],
         [0.0235, 0.9676, 0.7652, 0.7727, 0.1540],
         [0.8508, 0.2072, 0.0961, 0.3273, 0.3188]],

        [[0.6619, 0.2119, 0.3890, 0.2755, 0.4114],
         [0.8796, 0.8804, 0.0825, 0.4347, 0.8278],
         [0.1894, 0.6012, 0.0858, 0.3514, 0.4617],
         [0.0946, 0.5688, 0.4623, 0.4941, 0.5812]]])

In [4]:
x[:, 0:1, :].shape

torch.Size([2, 1, 5])

In [5]:
front=x[:, 0:1, :].repeat(1, 2, 1)
front.shape

torch.Size([2, 2, 5])

In [6]:
front

tensor([[[0.9361, 0.2419, 0.8914, 0.6563, 0.8088],
         [0.9361, 0.2419, 0.8914, 0.6563, 0.8088]],

        [[0.6619, 0.2119, 0.3890, 0.2755, 0.4114],
         [0.6619, 0.2119, 0.3890, 0.2755, 0.4114]]])

In [7]:
x.shape

torch.Size([2, 4, 5])

In [8]:
x[:,-1:, :].shape

torch.Size([2, 1, 5])

In [11]:
end=x[:,-1:,:].repeat(1, 2, 1)
end

tensor([[[0.8508, 0.2072, 0.0961, 0.3273, 0.3188],
         [0.8508, 0.2072, 0.0961, 0.3273, 0.3188]],

        [[0.0946, 0.5688, 0.4623, 0.4941, 0.5812],
         [0.0946, 0.5688, 0.4623, 0.4941, 0.5812]]])

In [12]:
end.shape

torch.Size([2, 2, 5])

In [14]:
x = torch.cat([front, x, end], dim=1)
x

tensor([[[0.9361, 0.2419, 0.8914, 0.6563, 0.8088],
         [0.9361, 0.2419, 0.8914, 0.6563, 0.8088],
         [0.9361, 0.2419, 0.8914, 0.6563, 0.8088],
         [0.8205, 0.0816, 0.7850, 0.3263, 0.6876],
         [0.0235, 0.9676, 0.7652, 0.7727, 0.1540],
         [0.8508, 0.2072, 0.0961, 0.3273, 0.3188],
         [0.8508, 0.2072, 0.0961, 0.3273, 0.3188],
         [0.8508, 0.2072, 0.0961, 0.3273, 0.3188]],

        [[0.6619, 0.2119, 0.3890, 0.2755, 0.4114],
         [0.6619, 0.2119, 0.3890, 0.2755, 0.4114],
         [0.6619, 0.2119, 0.3890, 0.2755, 0.4114],
         [0.8796, 0.8804, 0.0825, 0.4347, 0.8278],
         [0.1894, 0.6012, 0.0858, 0.3514, 0.4617],
         [0.0946, 0.5688, 0.4623, 0.4941, 0.5812],
         [0.0946, 0.5688, 0.4623, 0.4941, 0.5812],
         [0.0946, 0.5688, 0.4623, 0.4941, 0.5812]]])

In [15]:
x.shape

torch.Size([2, 8, 5])

In [20]:
avg_pool = nn.AvgPool1d(kernel_size=2, stride=1, padding=0)

In [21]:
avg_pool(x)

tensor([[[0.5890, 0.5666, 0.7738, 0.7325],
         [0.5890, 0.5666, 0.7738, 0.7325],
         [0.5890, 0.5666, 0.7738, 0.7325],
         [0.4511, 0.4333, 0.5557, 0.5070],
         [0.4956, 0.8664, 0.7690, 0.4633],
         [0.5290, 0.1516, 0.2117, 0.3230],
         [0.5290, 0.1516, 0.2117, 0.3230],
         [0.5290, 0.1516, 0.2117, 0.3230]],

        [[0.4369, 0.3005, 0.3323, 0.3435],
         [0.4369, 0.3005, 0.3323, 0.3435],
         [0.4369, 0.3005, 0.3323, 0.3435],
         [0.8800, 0.4815, 0.2586, 0.6312],
         [0.3953, 0.3435, 0.2186, 0.4066],
         [0.3317, 0.5155, 0.4782, 0.5376],
         [0.3317, 0.5155, 0.4782, 0.5376],
         [0.3317, 0.5155, 0.4782, 0.5376]]])