In [1]:
import torch
import torch.nn as nn

In [2]:
arr = torch.rand(3, 4, 5)

In [3]:
arr

tensor([[[0.9302, 0.7646, 0.8260, 0.0922, 0.1571],
         [0.1382, 0.7783, 0.9480, 0.9625, 0.5481],
         [0.8833, 0.7569, 0.0297, 0.3275, 0.9445],
         [0.7239, 0.9559, 0.0294, 0.2837, 0.8355]],

        [[0.0992, 0.8544, 0.2323, 0.5384, 0.4289],
         [0.3156, 0.0849, 0.5892, 0.2040, 0.0587],
         [0.1937, 0.7431, 0.5903, 0.1813, 0.8900],
         [0.2077, 0.6300, 0.3359, 0.2203, 0.6355]],

        [[0.4023, 0.5747, 0.9968, 0.7885, 0.0982],
         [0.1537, 0.1624, 0.7470, 0.8261, 0.6990],
         [0.7162, 0.4233, 0.6410, 0.1653, 0.9782],
         [0.0140, 0.4309, 0.2729, 0.8013, 0.6197]]])

In [6]:
arr[:, :, -1:]

tensor([[[0.1571],
         [0.5481],
         [0.9445],
         [0.8355]],

        [[0.4289],
         [0.0587],
         [0.8900],
         [0.6355]],

        [[0.0982],
         [0.6990],
         [0.9782],
         [0.6197]]])

In [7]:
f_dim = slice(-1,None)

In [9]:
arr[:, :, f_dim]

tensor([[[0.1571],
         [0.5481],
         [0.9445],
         [0.8355]],

        [[0.4289],
         [0.0587],
         [0.8900],
         [0.6355]],

        [[0.0982],
         [0.6990],
         [0.9782],
         [0.6197]]])

In [12]:
f_dim = slice(1, 4)

In [13]:
arr[:, :, f_dim]

tensor([[[0.7646, 0.8260, 0.0922],
         [0.7783, 0.9480, 0.9625],
         [0.7569, 0.0297, 0.3275],
         [0.9559, 0.0294, 0.2837]],

        [[0.8544, 0.2323, 0.5384],
         [0.0849, 0.5892, 0.2040],
         [0.7431, 0.5903, 0.1813],
         [0.6300, 0.3359, 0.2203]],

        [[0.5747, 0.9968, 0.7885],
         [0.1624, 0.7470, 0.8261],
         [0.4233, 0.6410, 0.1653],
         [0.4309, 0.2729, 0.8013]]])